<?php
 $session_id ='';
 if(!empty($this->session->userdata('session_data'))){
 $session = $this->session->userdata('session_data') ; //Retrive ur session
 $session_accont = $session['name'];
 $session_email = $session['email'];
 $walletaddress = $session['account'];
 @$logger_password = $session['password'];
 @$logger_private_key = $session['private_key'];
 header('Access-Control-Allow-Origin: *');
}
?>
<div class="play_page">
    <p><strong>ETHPlay Lottery</strong> gives players the chance to win huge prizes by betting on the outcome of numbers
        newly generated from the Ethereum transaction hash. Winning numbers are obtained from the latest transaction
        hash by our lottery software, with the last number from the end of the latest TxHash representing the winning
        number. An Ethereum TxHash is a 32-bit ID randomly generated by a sophisticated encryption algorithm and
        normally shown as a hex value. Our drawing process takes advantage of this truly random computation process to
        ensure its fairness and transparency.<p>
            <p>In short, your goal is to bet on the fifth number from the outcome of the last 5 digits of the first
                eligible TxHash’s from the next Ethereum block. You can bet on as few as one, and as many of 9 digits to
                increase your potential winnings!</p>
            <p>ETHPlay Lottery is a once-per-four-minutes game, running for a total of 360 rounds per day, 365 days per
                year non-stop.</p>

            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse1">Bet Rules<i class="fa fa-chevron-up" aria-hidden="true"></i></a>
                        </h4>
                    </div>
                    <div id="collapse1" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p><Strong>Betting Time</Strong>
                                The round number the bet belongs to is determined by the time that records the bet.</p>
                            <p>
                                Example. If a user’s bet played with time 14:19:59, then he is betting in round
                                #14:19:04, the winning number will be generated starting from 13:20:00. Player can
                                always check the round number and time the bet was placed.</p>
                        </div>
                      
                    </div>
                </div>
            </div>
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse2">Maximum Bets<i class="fa fa-chevron-up" aria-hidden="true"></i></a>
                        </h4>
                    </div>
                    <div id="collapse2" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p>Limit Per Order: The system currently implements a maximum bet of 0.25 Ether, and a minimum bet of 0.005 Ether per order.</p>
                            <p>
                            Limit Per Round: To ensure the long term viability of ETHPlay Lottery, there is also a maximum limit that can be placed by all players per round. The maximum bet amount that will be accepted by the system is equal to no more than 5% of the lottery balance.</p>
                        </div>
                        
                    </div>
                </div>
            </div>

            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse3">Ways to Play
                            <i class="fa fa-chevron-up" aria-hidden="true"></i>
                            </a>
                        </h4>
                    </div>
                    <div id="collapse3" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p>ETHPlay Lottery allows you to play in a variety of ways, giving you full control over your risk reward ratio. Currently, ETHPlay Lottery allows the following bets</p>
                            <p>1 Bit – Match last digit, win 10 x wager</p>
                            <p>Big/Small – Big (5-9) or Small (0-4) match the last digit, win 2 x wager</p>
                            <p>Odds/Even – Odd (1, 3, 5, 7, 9) or Even (0, 2, 4, 6, 8) match the last digit, win 2 x wager</p>

To maintain the platform’s daily operations, the system will take 5% from winning amounts. E.g. Rewards = (Bet Amount * Award Multiplier) * 0.95..</p>
                        </div>
                        
                    </div>
                </div>
            </div>

            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse4">Optional table format
                            <i class="fa fa-chevron-up" aria-hidden="true"></i>
                            </a>
                        </h4>
                    </div>
                    <div id="collapse4" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p>Bet Condition Win Multiplier</p>
                            <p>1 Bits Match the last digit 10 x wager</p>
                            <p>Big/Small Big (5-9) or Small (0-4) match last digit 2 x wager</p>
                            <p>Odds/Even Odd (1, 3, 5, 7, 9) or Even (0, 2, 4, 6, 8) match last digit 2 x wager.</p>
                            <p>
                            Limit Per Round: To ensure the long term viability of ETHPlay Lottery, there is also a maximum limit that can be placed by all players per round. The maximum bet amount that will be accepted by the system is equal to no more than 5% of the lottery balance.</p>
                        </div>
                        
                    </div>
                </div>
            </div>


            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse5">Deposits & Funds
                            <i class="fa fa-chevron-up" aria-hidden="true"></i>
                            </a>
                        </h4>
                    </div>
                    <div id="collapse5" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p>We do not keep your funds. When you open an account with ETHPlay.io, your own Ethereum wallet is created with a private key which you and only you can retrieve and manage</p>
                        </div>
                        
                    </div>
                </div>
            </div>
            
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse6">Blockchain Records
                            <i class="fa fa-chevron-up" aria-hidden="true"></i>
                            </a>
                        </h4>
                    </div>
                    <div id="collapse6" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p>Every bet placed on ETHPlay.io lottery is recorded in the transaction hash on the Ethereum blockchain.</p>
                        </div>
                        
                    </div>
                </div>
            </div>

            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse7">Deposits & Withdrawal
                            <i class="fa fa-chevron-up" aria-hidden="true"></i>
                            </a>
                        </h4>
                    </div>
                    <div id="collapse7" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p><strong>Deposits</strong>
                            When your wallet is created, simply send your desired funds to the address generated. The new balance will be displayed after confirmation by the blockchain.</p>
                            <p><strong>Withdrawal</strong>
                            Since you control your wallet and funds, you can withdraw your funds anytime to any Ethereum address.</p>
                            <p><strong>Other Currencies</strong>
                            We only support the Ethereum cryptocurrency at this time. 
                        <strong>DO NOT ATTEMPT TO SEND OTHER CURRENCY. YOU WILL LOSE YOUR FUNDS.</strong></p>
                        </div>
                        
                    </div>


                    <div id="collapse7" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p><strong>Accessing or creating a new account</strong>
                            Click on Login to access your account or to create a new account. Please choose a hard to guess password and store in a safe place.</p>
                            <ul>
                            <li>After logging in to your account, click on “My Account” to display your wallet address to use for depositing funds.</li>
                            <li>Once your wallet is funded you can start betting as described above.</li>
                            <li>When placing a bet, you wallet balance will be automatically updated depending on the outcome of your bet winning or losing.</li>
                            <li>In-case ETHPlay.io website goes down for any reason, we highly recommend saving your wallet private key in a safe place. To retrive the private key, please click on “My Account” and click “Private Key” renter your password to display.</li>
                            <li>To see a records of all your bets or outcome, click on “My Bets”.</li>
                            <li>To withdraw funds to other wallets, click on “My Account” and select Withdraw.</li>
    
                        </ul>

                        </div>
                        
                    </div>
                </div>
            </div>

</div>